defaults:
  - _self_
  - override hydra/hydra_logging: disabled
  - override hydra/job_logging: disabled

hydra:
  output_subdir: null
  run:
    dir: /workspace/faster-midog-plus/.mnt/scratch/outputs

wandb:
  entity: xmiklankova
  project: MIDOG-fasterRCNN

files:
  image_path: /mnt/datasets/MIDOGpp/images
  annotation_file: /mnt/datasets/MIDOGpp/images/MIDOG++.sqlite

data:
  patch_size: 512
  batch_size: 4 
  level: 0
  train_patches: 100
  valid_patches: 25
  tumortypes: human breast cancer

retinanet:
  scales: 0.2,0.4,0.6,0.8,1.0
  ratios: 1
  sizes: 32

training:
  lr: 5e-5
  num_epochs: 100
  checkpoint: all

x-validation:
  train: None
  valid: None




